import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useWalletConnect} from "@cityofzion/wallet-connect-sdk-react";
import { BaseDapi } from "@neongd/neo-dapi";
import { CONST, rpc, sc, wallet, tx, u,BigInteger} from "@cityofzion/neon-core";







export default function Home() {
  
  const func = async() => {
  
      // @ts-ignore
      const instance = new NEOLineN3.Init();
      // @ts-ignore
      // NEOLineN3 doesn't have getNetworks function
      const instance2 = new NEOLine.Init();
      const network = await instance2.getNetworks();
      const account = await instance.getAccount();
      const rpcClient = new rpc.RPCClient("https://rpc.splendor.network/prpc");
      const balance = await rpcClient.getNep17Balances(account.address);

      console.log(account.address);
      console.log(network.chainId);
      console.log(network.networks);
      console.log(network.defaultNetwork);
      console.log(balance)
      return {
        instance,
        account,
        network
      };
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <button onClick={func}>Connect Wallet and Console Log Test</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
