import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useWalletConnect} from "@cityofzion/wallet-connect-sdk-react";



export default function Home() {

  const wcSdk = useWalletConnect();
  const func = async() => {
    const { uri, approval } = await wcSdk.createConnection('neo3:mainnet', ['invokeFunction', 'testInvoke', 'signMessage', 'verifyMessage'])
    window.open(`https://neon.coz.io/connect?uri=${uri}`, '_blank')?.focus() // do whatever you want with the uri
    const session = await approval()
    wcSdk.setSession(session)
    console.log(session ? 'Connected successfully' : 'Connection refused')
  }
  if (wcSdk.isConnected()) {
    console.log(wcSdk.getAccountAddress()) // print the first connected account address
    console.log(wcSdk.getChainId()) // print the first connected account chain info
    console.log(wcSdk.session.namespaces); // print the blockchain dictionary with methods, accounts and events
    console.log(wcSdk.session.peer.metadata); // print the wallet metadata
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <button onClick={func}>Connect Wallet</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
